### ISSUE TITLE
[DB] Smoking Area, Info 테이블 column 추가

### ISSUE THREAD

**Issue by BlueBerrySoda** [Alpha-Damyo/BE#16]
현재 DB에 실내/실외와 관련된 column이 존재하지 않습니다.

해당 사항을 수정할 것인가요?

**Comment by guahama** [comment]
수정하는 것이 좋아 보입니다. 더 추가할 column이 있다면 취합해서 한 번에 수정하는 방향으로 하는 건 어떨까요?

**Comment by BlueBerrySoda** [comment]
그럼 오늘 회의에서 추가할 column에 대해 얘기하는 것으로 하겠습니다.

**Comment by BlueBerrySoda** [comment]
SmokingArea, Info 테이블 Tag 목록

- 개방 
- 폐쇄
- 청결  
- 더러움
- 환기
- 존재하지 않음

추가 column

- 실내
- 실외
- 크다  
- 작다
- 혼잡  
- 한산
- 좌석
